--- 
abstract: Adapter to use Log::Log4perl with Log::Any
author: 
  - Jonathan Swartz <swartz@pobox.com>
build_requires: 
  File::Temp: 0.20
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Log-Any-Adapter-Log-Log4perl
no_index: 
  directory: 
    - inc
    - t
requires: 
  Log::Any: 0.01
  Log::Log4perl: 1.00
  perl: 5.6.0
version: 0.01
